services:
  - type: web
    name: jeopardy-game
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    publishDir: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production