services:
  - type: web
    name: jeopardy-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    publishDir: .
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0