services:
  - type: web
    name: jeopardy-game
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    publishDir: .
    healthCheckPath: /health
    port: 3000
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000